export const LESSON_STATES = {
  STARTING: "LESSON_STARTING",
  INTRO: "LESSON_INTRO",
  LISTENING: "LESSON_LISTENING",
  PRONUNCIATION: "LESSON_PRONUNCIATION",
  WRITING: "LESSON_WRITING",
  RESULT: "LESSON_ENTRY_RESULT",
  REWARD: "LESSON_REWARD",
  PUNISHMENT: "LESSON_PUNISHMENT",
  SUMMARY: "LESSON_SUMMARY",
} as const;

export type LessonStateNames =
  (typeof LESSON_STATES)[keyof typeof LESSON_STATES];
