export const PLAYER_STATES = {
  IDLE: "PLAYER_IDLE",
  MOVING: "PLAYER_MOVING",
  SPEAKING: "PLAYER_SPEAKING",
  LISTENING: "PLAYER_LISTENING",
  SCARED: "PLAYER_SCARED",
  INCLINED: "PLAYER_INCLINED",
} as const;

export type PlayerStateNames =
  (typeof PLAYER_STATES)[keyof typeof PLAYER_STATES];
