export const LEARNING_NODE_STATES = {
  PLANT_LEARNING_NODE: "LEARNING_NODE_PLANT_LEARNING_NODE",
  SPROUT_IDLE: "LEARNING_NODE_SPROUT_IDLE",
  SPROUT_SPEAKING: "LEARNING_NODE_SPROUT_SPEAKING",
  HEAD_GROWING: "LEARNING_NODE_HEAD_GROWING",
  HEAD_IDLE: "LEARNING_NODE_HEAD_IDLE",
  HALF_BODY_GROWING: "LEARNING_NODE_HALF_BODY_GROWING",
  HALF_BODY_IDLE: "LEARNING_NODE_HALF_BODY_IDLE",
  COMPLETE_GROWING: "LEARNING_NODE_COMPLETE_GROWING",
  COMPLETE_LAUGHING: "LEARNING_NODE_COMPLETE_LAUGHING",
  COMPLETE_CRYING: "LEARNING_NODE_COMPLETE_CRYING",
  COMPLETE_RUNNING: "LEARNING_NODE_COMPLETE_RUNNING",
  COMPLETE_MERGING: "LEARNING_NODE_COMPLETE_MERGING",
  COMPLETE_CAPTURED: "LEARNING_NODE_COMPLETE_CAPTURED",
  DESTROY: "LEARNING_NODE_DESTROY",
} as const;

export type LearningNodeStateNames =
  (typeof LEARNING_NODE_STATES)[keyof typeof LEARNING_NODE_STATES];
