export const LEARNING_NODE_STATES = {
  SPROUTING: "LEARNING_NODE_SPROUTING",
  SPROUT_IDLE: "LEARNING_NODE_IDLE",
  SPROUT_TALKING: "LEARNING_NODE_SPROUT_TALKING",
  PUMPKIN_TRANSITION: "LEARNING_NODE_PUMPKIN_TRANSITION",
  PUMPKIN_IDLE: "LEARNING_NODE_PUMPKIN_IDLE",
  FULL_IDLE: "LEARNING_NODE_FULL_IDLE",
  FULL_WALKING: "LEARNING_NODE_FULL_WALKING",
} as const;

export type LearningNodeStateNames =
  (typeof LEARNING_NODE_STATES)[keyof typeof LEARNING_NODE_STATES];
