// Auto-generated by scripts/spritesheet/update-spritesheets-constants.mjs
// Do not edit manually.

export type SpritesheetEntry = {
  key: string;
  image: string;
  atlas: string;
};

export const SPRITESHEETS = {
  eliza: {
    idle: {
      key: 'eliza-idle',
      image: '/actors/eliza/idle/spritesheet.png',
      atlas: '/actors/eliza/idle/spritesheet.json'
    },
    sowing: {
      key: 'eliza-sowing',
      image: '/actors/eliza/sowing/spritesheet.png',
      atlas: '/actors/eliza/sowing/spritesheet.json'
    },
    teaching: {
      key: 'eliza-teaching',
      image: '/actors/eliza/teaching/spritesheet.png',
      atlas: '/actors/eliza/teaching/spritesheet.json'
    }
  }
} as const;

export type SpriteActor = keyof typeof SPRITESHEETS;

export type ActorSpritesheets<TActor extends SpriteActor> =
  (typeof SPRITESHEETS)[TActor];

export type SpriteAnimation<TActor extends SpriteActor> =
  keyof ActorSpritesheets<TActor>;
