// Auto-generated by scripts/spritesheet/update-spritesheets-constants.mjs
// Do not edit manually.

export type SpritesheetEntry = {
  key: string;
  image: string;
  atlas: string;
};

export const SPRITESHEETS = {
  jailer: {
    idle: {
      key: 'jailer-idle',
      image: '/actors/jailer/idle/spritesheet.png',
      atlas: '/actors/jailer/idle/spritesheet.json'
    },
    talking: {
      key: 'jailer-talking',
      image: '/actors/jailer/talking/spritesheet.png',
      atlas: '/actors/jailer/talking/spritesheet.json'
    }
  },
  learningNode: {
    floor_transition: {
      key: 'learningNode-floor_transition',
      image: '/actors/learningNode/floor_transition/spritesheet.png',
      atlas: '/actors/learningNode/floor_transition/spritesheet.json'
    },
    pumpkin_default: {
      key: 'learningNode-pumpkin_default',
      image: '/actors/learningNode/pumpkin_default/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_default/spritesheet.json'
    },
    pumpkin_evil_idle: {
      key: 'learningNode-pumpkin_evil_idle',
      image: '/actors/learningNode/pumpkin_evil_idle/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_evil_idle/spritesheet.json'
    },
    pumpkin_evil_walking: {
      key: 'learningNode-pumpkin_evil_walking',
      image: '/actors/learningNode/pumpkin_evil_walking/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_evil_walking/spritesheet.json'
    },
    pumpkin_full: {
      key: 'learningNode-pumpkin_full',
      image: '/actors/learningNode/pumpkin_full/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_full/spritesheet.json'
    },
    pumpkin_full_failure: {
      key: 'learningNode-pumpkin_full_failure',
      image: '/actors/learningNode/pumpkin_full_failure/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_full_failure/spritesheet.json'
    },
    pumpkin_full_success: {
      key: 'learningNode-pumpkin_full_success',
      image: '/actors/learningNode/pumpkin_full_success/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_full_success/spritesheet.json'
    },
    pumpkin_full_walking: {
      key: 'learningNode-pumpkin_full_walking',
      image: '/actors/learningNode/pumpkin_full_walking/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_full_walking/spritesheet.json'
    },
    pumpkin_out_idle: {
      key: 'learningNode-pumpkin_out_idle',
      image: '/actors/learningNode/pumpkin_out_idle/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_out_idle/spritesheet.json'
    },
    pumpkin_side_idle: {
      key: 'learningNode-pumpkin_side_idle',
      image: '/actors/learningNode/pumpkin_side_idle/spritesheet.png',
      atlas: '/actors/learningNode/pumpkin_side_idle/spritesheet.json'
    },
    sprouting_idle: {
      key: 'learningNode-sprouting_idle',
      image: '/actors/learningNode/sprouting_idle/spritesheet.png',
      atlas: '/actors/learningNode/sprouting_idle/spritesheet.json'
    },
    sprouting_talking: {
      key: 'learningNode-sprouting_talking',
      image: '/actors/learningNode/sprouting_talking/spritesheet.png',
      atlas: '/actors/learningNode/sprouting_talking/spritesheet.json'
    },
    sprouting_transition: {
      key: 'learningNode-sprouting_transition',
      image: '/actors/learningNode/sprouting_transition/spritesheet.png',
      atlas: '/actors/learningNode/sprouting_transition/spritesheet.json'
    }
  },
  memoryGuardian: {
    inclined_idle: {
      key: 'memoryGuardian-inclined_idle',
      image: '/actors/memoryGuardian/inclined_idle/spritesheet.png',
      atlas: '/actors/memoryGuardian/inclined_idle/spritesheet.json'
    },
    inclined_speaking: {
      key: 'memoryGuardian-inclined_speaking',
      image: '/actors/memoryGuardian/inclined_speaking/spritesheet.png',
      atlas: '/actors/memoryGuardian/inclined_speaking/spritesheet.json'
    },
    inclining: {
      key: 'memoryGuardian-inclining',
      image: '/actors/memoryGuardian/inclining/spritesheet.png',
      atlas: '/actors/memoryGuardian/inclining/spritesheet.json'
    },
    normal_idle: {
      key: 'memoryGuardian-normal_idle',
      image: '/actors/memoryGuardian/normal_idle/spritesheet.png',
      atlas: '/actors/memoryGuardian/normal_idle/spritesheet.json'
    }
  },
  player: {
    idle: {
      key: 'player-idle',
      image: '/actors/player/idle/spritesheet.png',
      atlas: '/actors/player/idle/spritesheet.json'
    },
    inclined: {
      key: 'player-inclined',
      image: '/actors/player/inclined/spritesheet.png',
      atlas: '/actors/player/inclined/spritesheet.json'
    },
    move: {
      key: 'player-move',
      image: '/actors/player/move/spritesheet.png',
      atlas: '/actors/player/move/spritesheet.json'
    },
    talking: {
      key: 'player-talking',
      image: '/actors/player/talking/spritesheet.png',
      atlas: '/actors/player/talking/spritesheet.json'
    }
  },
  punisher: {
    idle: {
      key: 'punisher-idle',
      image: '/actors/punisher/idle/spritesheet.png',
      atlas: '/actors/punisher/idle/spritesheet.json'
    },
    running: {
      key: 'punisher-running',
      image: '/actors/punisher/running/spritesheet.png',
      atlas: '/actors/punisher/running/spritesheet.json'
    },
    walking: {
      key: 'punisher-walking',
      image: '/actors/punisher/walking/spritesheet.png',
      atlas: '/actors/punisher/walking/spritesheet.json'
    }
  },
  tutor: {
    idle: {
      key: 'tutor-idle',
      image: '/actors/tutor/idle/spritesheet.png',
      atlas: '/actors/tutor/idle/spritesheet.json'
    },
    leaving: {
      key: 'tutor-leaving',
      image: '/actors/tutor/leaving/spritesheet.png',
      atlas: '/actors/tutor/leaving/spritesheet.json'
    },
    sowing: {
      key: 'tutor-sowing',
      image: '/actors/tutor/sowing/spritesheet.png',
      atlas: '/actors/tutor/sowing/spritesheet.json'
    },
    teaching: {
      key: 'tutor-teaching',
      image: '/actors/tutor/teaching/spritesheet.png',
      atlas: '/actors/tutor/teaching/spritesheet.json'
    }
  }
} as const;

export type SpriteActor = keyof typeof SPRITESHEETS;

export type ActorSpritesheets<TActor extends SpriteActor> =
  (typeof SPRITESHEETS)[TActor];

export type SpriteAnimation<TActor extends SpriteActor> =
  keyof ActorSpritesheets<TActor>;
