export const DREAM_SCENE_STATES = {
  INTRO: "SCENE_INTRO",
  IDLE: "SCENE_IDLE",
  PERFORMING_ACTION: "PERFORMING_ACTION",
  PERFORMING_LESSON: "PERFORMING_LESSON",
  POST_LESSON: "POST_LESSON",
} as const;

export type SceneStateNames =
  (typeof DREAM_SCENE_STATES)[keyof typeof DREAM_SCENE_STATES];
