export const DREAM_SCENE_STATES = {
  SCENE_INTRO: "SCENE_INTRO",
  IDLE: "SCENE_IDLE",
  LESSON_STARTING: "LESSON_STARTING",
  LESSON_INTRO: "LESSON_INTRO",
  LISTENING: "LESSON_LISTENING",
  PRONUNCIATION: "LESSON_PRONUNCIATION",
  WRITING: "LESSON_WRITING",
  RESULT: "LESSON_RESULT",
  REWARD: "LESSON_REWARD",
  PUNISHMENT: "LESSON_PUNISHMENT",
  SUMMARY: "LESSON_SUMMARY",
  SCENE_TRANSITION: "SCENE_TRANSITION",
} as const;

export type SceneStateNames =
  (typeof DREAM_SCENE_STATES)[keyof typeof DREAM_SCENE_STATES];
