export const LESSON_STATES = {
  LESSON_START: "LESSON_START",
  ENTRY_INTRODUCTION: "LESSON_ENTRY_INTRODUCTION",
  LISTENING: "LESSON_LISTENING",
  PRONUNCIATION: "LESSON_PRONUNCIATION",
  WRITING: "LESSON_WRITING",
  ENTRY_RESULT: "LESSON_ENTRY_RESULT",
  REWARD: "LESSON_REWARD",
  PUNISHMENT: "LESSON_PUNISHMENT",
  ENTRY_SUMMARY: "LESSON_ENTRY_SUMMARY",
  LESSON_SUMMARY: "LESSON_SUMMARY",
} as const;

export type LessonStateNames =
  (typeof LESSON_STATES)[keyof typeof LESSON_STATES];
