export const LESSON_STATES = {
  TRANSITION: "TRANSITION",
  LESSON: {
    START: "LESSON_START",
    INTRODUCTION: "LESSON_INTRODUCTION",
  },

  GROWTH: {
    SOWING: "SOWING",
    SEED_FALLING: "SEED_FALLING",
    SPROUTING: "SPROUTING",
  },

  LISTENING: {
    INTRO: "LISTENING_INTRODUCTION",
    CHALLENGE: "LISTENING_CHALLENGE",
    RESULT: "LISTENING_RESULT",
  },

  PRONUNCIATION: {
    INTRO: "PRONUNCIATION_INTRODUCTION",
    CHALLENGE: "PRONUNCIATION_CHALLENGE",
    RESULT: "PRONUNCIATION_RESULT",
  },

  WRITING: {
    INTRO: "WRITING_INTRODUCTION",
    CHALLENGE: "WRITING_CHALLENGE",
    RESULT: "WRITING_RESULT",
  },

  ENTRY: {
    RESULT: "ENTRY_RESULT",
  },

  REWARD: {
    RUNNING: "REWARD_RUNNING",
    MERGING: "REWARD_MERGING",
  },

  PUNISHMENT: {
    APPEAR: "PUNISHMENT_APPEAR",
    CAPTURE: "PUNISHMENT_CAPTURE",
    FLEEING: "PUNISHMENT_FLEEING",
  },
} as const;
