export const LESSON_STATES = {
  BEGINNING: {
    LESSON_START: "LESSON_START",
    LESSON_INTRODUCTION: "LESSON_INTRODUCTION",
  },

  FARMING: {
    SOWING: "SOWING",
    SEED_FALLING: "SEED_FALLING",
    SPROUTING: "SPROUTING",
  },

  LISTENING: {
    INTRO: "LISTENING_INTRODUCTION",
    CHALLENGE: "LISTENING_CHALLENGE",
    RESULT: "LISTENING_RESULT",
  },

  PRONUNCIATION: {
    INTRO: "PRONUNCIATION_INTRODUCTION",
    CHALLENGE: "PRONUNCIATION_CHALLENGE",
    RESULT: "PRONUNCIATION_RESULT",
  },

  WRITING: {
    INTRO: "WRITING_INTRODUCTION",
    CHALLENGE: "WRITING_CHALLENGE",
    RESULT: "WRITING_RESULT",
  },

  RESULT: {
    ENTRY_RESULT: "ENTRY_RESULT",
  },

  REWARD: {
    RUNNING: "REWARD_RUNNING",
    MERGING: "REWARD_MERGING",
  },

  PUNISHMENT: {
    APPEAR: "PUNISHMENT_APPEAR",
    CAPTURE: "PUNISHMENT_CAPTURE",
    FLEEING: "PUNISHMENT_FLEEING",
  },
} as const;

export type LessonStateNames = {
  [K in keyof typeof LESSON_STATES]: (typeof LESSON_STATES)[K][keyof (typeof LESSON_STATES)[K]];
}[keyof typeof LESSON_STATES];
