import { LESSON_MIN_SCORE_DEFAULT } from "@/constants/game";
import { LESSON_STATES } from "./lessonStates";

type Ctx = {
  score: number;
  minScore: number;
};

type Transition = string | ((ctx: Ctx) => string);

const STATE_TRANSITIONS: Record<string, Transition> = {
  [LESSON_STATES.LESSON.START]: LESSON_STATES.LESSON.INTRODUCTION,
  [LESSON_STATES.LESSON.INTRODUCTION]: LESSON_STATES.GROWTH.SOWING,

  [LESSON_STATES.GROWTH.SOWING]: LESSON_STATES.GROWTH.SEED_FALLING,
  [LESSON_STATES.GROWTH.SEED_FALLING]: LESSON_STATES.GROWTH.SPROUTING,
  [LESSON_STATES.GROWTH.SPROUTING]: LESSON_STATES.LISTENING.INTRO,

  [LESSON_STATES.LISTENING.INTRO]: LESSON_STATES.LISTENING.CHALLENGE,
  [LESSON_STATES.LISTENING.CHALLENGE]: LESSON_STATES.LISTENING.RESULT,
  [LESSON_STATES.LISTENING.RESULT]: LESSON_STATES.PRONUNCIATION.INTRO,

  [LESSON_STATES.PRONUNCIATION.INTRO]: LESSON_STATES.PRONUNCIATION.CHALLENGE,
  [LESSON_STATES.PRONUNCIATION.CHALLENGE]: LESSON_STATES.PRONUNCIATION.RESULT,
  [LESSON_STATES.PRONUNCIATION.RESULT]: LESSON_STATES.WRITING.INTRO,

  [LESSON_STATES.WRITING.INTRO]: LESSON_STATES.WRITING.CHALLENGE,
  [LESSON_STATES.WRITING.CHALLENGE]: LESSON_STATES.WRITING.RESULT,
  [LESSON_STATES.WRITING.RESULT]: LESSON_STATES.ENTRY.RESULT,

  [LESSON_STATES.ENTRY.RESULT]: ({ score, minScore }) =>
    score >= minScore
      ? LESSON_STATES.REWARD.RUNNING
      : LESSON_STATES.PUNISHMENT.APPEAR,

  [LESSON_STATES.REWARD.RUNNING]: LESSON_STATES.REWARD.MERGING,
  [LESSON_STATES.REWARD.MERGING]: LESSON_STATES.LESSON.START,

  [LESSON_STATES.PUNISHMENT.APPEAR]: LESSON_STATES.PUNISHMENT.CAPTURE,
  [LESSON_STATES.PUNISHMENT.CAPTURE]: LESSON_STATES.PUNISHMENT.FLEEING,
  [LESSON_STATES.PUNISHMENT.FLEEING]: LESSON_STATES.LESSON.START,
};

export function getNextState(
  currentState: string,
  score: number,
  minScore = LESSON_MIN_SCORE_DEFAULT,
) {
  const transition = STATE_TRANSITIONS[currentState];
  if (!transition) return LESSON_STATES.LESSON.START;

  if (typeof transition === "function") {
    return transition({ score, minScore });
  }

  return transition;
}
