export const PUMPKIN_STATES = {
  PLANT_PUMPKIN: "PUMPKIN_PLANT_PUMPKIN",
  SPROUT_IDLE: "PUMPKIN_SPROUT_IDLE",
  SPROUT_SPEAKING: "PUMPKIN_SPROUT_SPEAKING",
  HEAD_GROWING: "PUMPKIN_HEAD_GROWING",
  HEAD_IDLE: "PUMPKIN_HEAD_IDLE",
  HALF_BODY_GROWING: "PUMPKIN_HALF_BODY_GROWING",
  HALF_BODY_IDLE: "PUMPKIN_HALF_BODY_IDLE",
  COMPLETE_GROWING: "PUMPKIN_COMPLETE_GROWING",
  COMPLETE_LAUGHING: "PUMPKIN_COMPLETE_LAUGHING",
  COMPLETE_CRYING: "PUMPKIN_COMPLETE_CRYING",
  COMPLETE_RUNNING: "PUMPKIN_COMPLETE_RUNNING",
  COMPLETE_MERGING: "PUMPKIN_COMPLETE_MERGING",
  COMPLETE_CAPTURED: "PUMPKIN_COMPLETE_CAPTURED",
  DESTROY: "PUMPKIN_DESTROY",
} as const;

export type PumpkinStateNames =
  (typeof PUMPKIN_STATES)[keyof typeof PUMPKIN_STATES];
